# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - run: pnpm i
      - run: npm run build

      - uses: softprops/action-gh-release@v1
        with:
          files: upx/*
          draft: true
